#!/usr/bin/env python3

#Code samples for Ryan from Dad

import cozmo
from cozmo.util import degrees, distance_mm, speed_mmps


def cozmo_talk(robot: cozmo.robot.Robot):
    #First words Ryan :-)
    robot.say_text("Hello Ryan").wait_for_completed()


def cozmo_left_turn(robot: cozmo.robot.Robot):
    #Move and take a left
    robot.drive_straight(distance_mm(150), speed_mmps(50)).wait_for_completed()
    robot.turn_in_place(degrees(90)).wait_for_completed()


def cozmo_count(robot: cozmo.robot.Robot):
    #Voice Count to 3
    for i in range(3):
        robot.say_text(str(i+1)).wait_for_completed()


def cozmo_drive_square(robot: cozmo.robot.Robot):
    #Make a small square
    for _ in range(4):
        robot.drive_straight(distance_mm(150), speed_mmps(50)).wait_for_completed()
        robot.turn_in_place(degrees(90)).wait_for_completed()


def cozmo_program(robot: cozmo.robot.Robot):
    print('Hello World!')
    cozmo_talk(robot)
    cozmo_left_turn(robot)
    cozmo_count(robot)
    cozmo_drive_square(robot)


cozmo.run_program(cozmo_program)

